### ISSUE TITLE
Add my ESP-IDF port of Examples?

### ISSUE THREAD

**Issue by dleslie** [chrisdiana/awesome-odroid-go#1]
Could you consider adding my port of numerous ODROID-GO examples to the ESP-IDF framework? It's a non-trivial task to move them from the Arduino IDE to the ESP-IDF toolchain, and requires some changes to the ODROID-GO component as well.

https://github.com/dleslie/odroid-go-examples-for-esp-idf

**Comment by chrisdiana** [comment]
Thank you for the idea! No problem. Would you mind submitting a PR with what you are thinking @dleslie?
